// Code generated by 'option-gen'. DO NOT EDIT.

package istio

import (
	prompt "github.com/c-bata/go-prompt"
)

var clusterInfoOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--include-extended-apis", Description: "If true, include definitions of new APIs via calls to the API server. [default true]"},
}
